-- MySQL Script generated by MySQL Workbench
-- Sun 27 Mar 2022 02:19:06 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kuca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kuca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kuca` DEFAULT CHARACTER SET cp1250 ;
USE `kuca` ;

-- -----------------------------------------------------
-- Table `kuca`.`korespondencija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kuca`.`korespondencija` (
  `idkorespondencija` INT(11) NOT NULL AUTO_INCREMENT,
  `cfrom` INT(11) NULL DEFAULT NULL,
  `cto` INT(11) NULL DEFAULT NULL,
  `vrijeme` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `poruka` VARCHAR(450) NULL DEFAULT NULL,
  `procitana` TINYINT(4) NULL DEFAULT '0',
  PRIMARY KEY (`idkorespondencija`),
  INDEX `to_fk_idx` (`cto` ASC) VISIBLE,
  INDEX `from_fk_idx` (`cfrom` ASC) VISIBLE,
  FULLTEXT INDEX `poruka` (`poruka`) VISIBLE,
  CONSTRAINT `from_fk`
    FOREIGN KEY (`cfrom`)
    REFERENCES `kuca`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `to_fk`
    FOREIGN KEY (`cto`)
    REFERENCES `kuca`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = cp1250;


-- -----------------------------------------------------
-- Table `kuca`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kuca`.`korisnik` (
  `idkorisnik` INT(11) NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NULL DEFAULT NULL,
  `prezime` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `user_name` VARCHAR(45) NULL DEFAULT NULL,
  `biografija` VARCHAR(450) NULL DEFAULT NULL,
  `fotografija` BLOB NULL DEFAULT NULL,
  `datumrodjenja` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idkorisnik`),
  UNIQUE INDEX `idx_korisnik_email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = cp1250;


-- -----------------------------------------------------
-- Table `kuca`.`plata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kuca`.`plata` (
  `idkorisnik` INT(11) NOT NULL,
  `iznos` DECIMAL(9,2) NULL DEFAULT NULL,
  `datum` DATE NULL DEFAULT NULL,
  `isplacena` TINYINT(4) NULL DEFAULT '0',
  `idtip_zaposlenja` INT(11) NULL DEFAULT NULL,
  INDEX `idtip_zaposlenja_idx` (`idtip_zaposlenja` ASC) VISIBLE,
  INDEX `idkorisnik_fk_idx` (`idkorisnik` ASC) VISIBLE,
  CONSTRAINT `idkorisnik_fk`
    FOREIGN KEY (`idkorisnik`)
    REFERENCES `kuca`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idtip_zaposlenja`
    FOREIGN KEY (`idtip_zaposlenja`)
    REFERENCES `kuca`.`tip_zaposlenja` (`idtip_zaposlenja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = cp1250;


-- -----------------------------------------------------
-- Table `kuca`.`tip_zaposlenja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kuca`.`tip_zaposlenja` (
  `idtip_zaposlenja` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtip_zaposlenja`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = cp1250;

USE `kuca` ;

-- -----------------------------------------------------
-- Placeholder table for view `kuca`.`korisnikview`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kuca`.`korisnikview` (`ime` INT, `prezime` INT, `datumrodjenja` INT);

-- -----------------------------------------------------
-- procedure brisi_korisnika
-- -----------------------------------------------------

DELIMITER $$
USE `kuca`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `brisi_korisnika`(p_idkorisnik int)
BEGIN
delete from kuca.korisnik where idkorisnik = p_idkorisnik;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure brisi_platu
-- -----------------------------------------------------

DELIMITER $$
USE `kuca`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `brisi_platu`(p_idkorisnik int,p_datum date)
BEGIN
delete from kuca.plata where idkorisnik=p_idkorisnik and datum=p_datum;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure brisi_poruku
-- -----------------------------------------------------

DELIMITER $$
USE `kuca`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `brisi_poruku`(p_idkorespondencija int)
BEGIN
delete from kuca.korespondencija where idkorespondencija=p_idkorespondencija;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function broj_poruka
-- -----------------------------------------------------

DELIMITER $$
USE `kuca`$$
CREATE DEFINER=`admin`@`%` FUNCTION `broj_poruka`(p_idkorisnik int) RETURNS int(11)
BEGIN
select count(*) into @brojporuka from kuca.korespondencija where cfrom=p_idkorisnik;
RETURN @brojporuka;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure izmijeni_korisnika
-- -----------------------------------------------------

DELIMITER $$
USE `kuca`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `izmijeni_korisnika`(p_idkorisnik int, p_ime varchar(45), p_prezime varchar(45), p_datum_rodjenja date, p_email varchar(45), p_user_name varchar(45), p_kratka_biografija text, p_fotografija varchar(255))
BEGIN
update kuca.korisnik
set  
`ime`= p_ime,
`prezime`=p_prezime,
`datum_rodjenja`=p_datum_rodjenja,
`email`=p_email,
`user_name`=p_user_name,
`kratka_biografija`=p_kratka_biografija,
`fotografija`=load_file(p_fotografija)
where
idkorisnik=p_idkorisnik;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure izmijeni_platu
-- -----------------------------------------------------

DELIMITER $$
USE `kuca`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `izmijeni_platu`(p_idkorisnik int,p_iznos decimal(9,2), p_datum date)
BEGIN
update kuca.plata
set
iznos=p_iznos
where 
idkorisnik=p_idkorisnik and datum=p_datum;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure izmijeni_poruku
-- -----------------------------------------------------

DELIMITER $$
USE `kuca`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `izmijeni_poruku`(p_idkorespondencija int, p_poruka text)
BEGIN
update kuca.korespondencijad
set poruka=p_poruka
where 
idkorespondencija=p_idkorespondencija;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure unesi_poruku
-- -----------------------------------------------------

DELIMITER $$
USE `kuca`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `unesi_poruku`(p_cfrom varchar(45),p_cto varchar(45), p_poruka text)
BEGIN
insert into kuca.korespondencija(cfrom,cto,poruka)
values(p_cfrom,p_cto,p_poruka);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure unos_korisnika
-- -----------------------------------------------------

DELIMITER $$
USE `kuca`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `unos_korisnika`(p_ime varchar(45), p_prezime varchar(45), p_datum_rodjenja date, p_email varchar(45), p_user_name varchar(45), p_biografija text, p_fotografija varchar(255))
BEGIN
insert into kuca.korisnik(ime,prezime,datumrodjenja,email,user_name, biografija, fotografija)
values 
(p_ime, p_prezime, p_datum_rodjenja, p_email, p_user_name, p_biografija, p_fotografija);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure unos_plate
-- -----------------------------------------------------

DELIMITER $$
USE `kuca`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `unos_plate`(p_idkorisnik int, p_iznos decimal(9,2), p_datum date, p_idtip_zaposlenja int)
BEGIN
insert into kuca.plata(idkorisnik,iznos,datum,idtip_zaposlenja)
values (p_idkorisnik,p_iznos,p_datum,p_idtip_zaposlenja);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `kuca`.`korisnikview`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kuca`.`korisnikview`;
USE `kuca`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`admin`@`%` SQL SECURITY DEFINER VIEW `kuca`.`korisnikview` AS select `kuca`.`korisnik`.`ime` AS `ime`,`kuca`.`korisnik`.`prezime` AS `prezime`,`kuca`.`korisnik`.`datumrodjenja` AS `datumrodjenja` from `kuca`.`korisnik`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
